export const constants = {
    UPDATE_FACTORY_CONTRACT: "UPDATE_FACTORY_CONTRACT",
    UPDATE_TEMPLATE_CONTRACT: "UPDATE_TEMPLATE_CONTRACT",
    UPDATE_METAMASK_ACCOUNT: "UPDATE_METAMASK_ACCOUNT"
};

export default constants;