export const constants = {
    UPDATE_CRYPTO: "UPDATE_CRYPTO",
    UPDATE_ALL_CRYPTO: "UPDATE_ALL_CRYPTO",
    UPDATE_MARKET_DATA: "UPDATE_MARKET_DATA",
    UPDATE_FEEDS: "UPDATE_FEEDS",
    UPDATE_TRADE_TOKENS: "UPDATE_TRADE_TOKENS",
    UPDATE_DIVIDEND: "UPDATE_DIVIDEND_FUND",
    START_TRANSACTION: "START_TRANSACTION",
    UPDATE_TRANSACTION_STATUS: "UPDATE_TRANSACTION_STATUS",
    END_TRANSACTION: "END_TRANSACTION",
    RESET_ACCOUNT: "RESET_ACCOUNT",
    UPDATE_ACCOUNT: "UPDATE_ACCOUNT",
    IS_LOADING_DIVIDEND: "IS_LOADING_DIVIDEND",
    IS_LOADING_MARKET_DATA: "IS_LOADING_MARKET_DATA",
    IS_LOADING_FEEDS: "IS_LOADING_FEEDS",
    IS_LOADING_CRYPTO: "IS_LOADING_CRYPTO"
};

export default constants;