export const constants = {
    UPDATE_CRYPTO: "UPDATE_CRYPTO",
    UPDATE_ALL_CRYPTO: "UPDATE_ALL_CRYPTO",
    UPDATE_MARKET_DATA: "UPDATE_MARKET_DATA",
    UPDATE_FEEDS: "UPDATE_FEEDS",
    UPDATE_TRADE_STATUS: "UPDATE_TRADE_STATUS",
    IS_LOADING_MARKET_DATA: "IS_LOADING_MARKET_DATA",
    IS_LOADING_FEEDS: "IS_LOADING_FEEDS",
    IS_LOADING_CRYPTO: "IS_LOADING_CRYPTO"
};

export default constants;