export const constants = {
    LOAD_SETTINGS: "LOAD_SETTINGS",
    UPDATE_METAMASK_ACCOUNT: "UPDATE_METAMASK_ACCOUNT",
    UPDATE_USER: "UPDATE_USER",
    UPDATE_SUBSCRIPTION_TYPES: "UPDATE_SUBSCRIPTION_TYPES",
    UPDATE_SUBSCRIBERS: "UPDATE_SUBSCRIBERS",
    UPDATE_SUBSCRIPTION_CONTRACTS: "UPDATE_SUBSCRIPTION_CONTRACTS",
    UPDATE_SUBSCRIPTIONS: "UPDATE_SUBSCRIPTIONS",
    UPDATE_USERS: "UPDATE_USERS",
    UPDATE_ETHEREUM_CONVERSION_RATES: "UPDATE_ETHEREUM_CONVERSION_RATES",
    UPDATE_LIVE_SUBSCRIPTION_CONTRACTS: "UPDATE_LIVE_SUBSCRIPTION_CONTRACTS",
    UPDATE_SUBSCRIPTION_DETAILS: "UPDATE_SUBSCRIPTION_DETAILS",
    UPDATE_TRIAL_SUBSCRIPTION_DETAILS: "UPDATE_TRIAL_SUBSCRIPTION_DETAILS",
    ADD_LIVE_SUBSCRIPTION_CONTRACTS: "ADD_LIVE_SUBSCRIPTION_CONTRACTS",
    EDIT_CONTRACT: "EDIT_CONTRACT"
};

export default constants;