export const constants = {
    LOAD_SETTINGS: "LOAD_SETTINGS",
    UPDATE_METAMASK_ACCOUNT: "UPDATE_METAMASK_ACCOUNT",
    UPDATE_USER: "UPDATE_USER",
    UPDATE_SUBSCRIPTION_TYPES: "UPDATE_SUBSCRIPTION_TYPES",
    UPDATE_SUBSCRIBERS: "UPDATE_SUBSCRIBERS",
    UPDATE_SUBSCRIPTION_CONTRACTS: "UPDATE_SUBSCRIPTION_CONTRACTS",
    UPDATE_SUBSCRIPTIONS: "UPDATE_SUBSCRIPTIONS"
};

export default constants;